name = "forthread"
version = "3.0.0"
license = "MIT"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"
categories = ["multithreading"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]
for_fifo_queue = { git = "https://github.com/jordan4ibanez/for_fifo_queue" }

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
